services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-asset-management}:${TAG:-latest}${ENV:-}
    env_file:
      - .env.${ENVIRONMENT:-dev}
    environment:
      - DB_HOST=host.docker.internal
    volumes:
      - .:/app
      - ~/Desktop/stock_plots:/app/stock_plots
      - ~/Desktop/analysis:/app/analysis
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge