version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-my-app}:${TAG:-latest}${ENV:-}
    env_file:
      - .env.${ENVIRONMENT:-dev}
    environment:
      - DB_HOST=host.docker.internal
    volumes:
      - .:/app
    networks:
      - app-network
    extra_hosts:  # Add this section for macOS
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge